### ISSUE TITLE
Math 411 won't display from the what is cmd

### ISSUE THREAD

**Issue by AndrewMead10** [daniel-melanson/umass-cics-community-bot#10]
When you do "What is math 411", the bot does not respond. The issue is most likely caused by the fact that the math 411 course listings start at 411.2 instead of 411.1

**Comment by daniel-melanson** [comment]
[@1ef28b5](https://github.com/daniel-melanson/UMass-CICS-Discord-Bot/commit/534c0625167df99a9a2818c91865abe2dbae57a7#diff-a829455ab1390c338cff5d6a389709bf)

**Comment by LTSENG01** [comment]
Not sure how to approach this issue right away. If we use the same approach, we could look for classes from no "dot" all the way through ".9" or something.

We could also find all classes ~the~ that begin with "411" and return the first element of the Array.

**Comment by daniel-melanson** [comment]
Seems to be an issue with the scraping. The "." in the class names differentiates sections. Descriptions of the course are the same. Thus a single entry for the course should be made.

**Comment by LTSENG01** [comment]
Yeah it's definitely in the scraping side of things and not the class command itself

**Comment by daniel-melanson** [comment]
[fix](https://github.com/daniel-melanson/UMass-CICS-Discord-Bot/commit/f83e8b9d2a494bb6582029a98d45fbfacf8b21da)
