### ISSUE TITLE
Add documentation for getting rid of roles

### ISSUE THREAD

**Issue by LTSENG01** [daniel-melanson/umass-cics-community-bot#13]
I can do it at some point later if nobody else wants to.

**Comment by daniel-melanson** [comment]
As in add information to the `!roles` command?

**Comment by LTSENG01** [comment]
Either there or under `!role` – Use this command to get **and remove roles**. I think Thomas suggested it under the `!help` command as well.

**Comment by daniel-melanson** [comment]
I think inside the `!roles` embedded message would be good. As well as inside the description of `!role`.
